// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDataDir():Promise<string>;

export function BackendOfflineReason():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function Ping():Promise<string>;

export function StartPatchUpdate(arg1:string):Promise<void>;
