// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function BackendOfflineReason() {
  return window['go']['main']['App']['BackendOfflineReason']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function StartPatchUpdate(arg1) {
  return window['go']['main']['App']['StartPatchUpdate'](arg1);
}
