/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs (newest first) */
        get: operations["listJobs"];
        put?: never;
        /** Submit a new transcription job */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a job by ID */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running or queued job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job progress snapshot for polling */
        get: operations["getJobProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/midi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the MIDI output for a completed job */
        get: operations["downloadMidi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine and dependency health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobState: "queued" | "running" | "retrying" | "completed" | "failed" | "cancelled";
        Job: {
            id: string;
            state: components["schemas"]["JobState"];
            /** Format: uri */
            youtube_url?: string;
            engine: string;
            /** @enum {string} */
            device: "cpu" | "cuda";
            start_sec?: number;
            error_code?: string;
            error_message?: string;
            attempt: number;
            max_attempts: number;
            /** Format: int64 */
            download_ms?: number;
            /** Format: int64 */
            inference_ms?: number;
            /** Format: int64 */
            total_ms?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        JobProgress: {
            job_id: string;
            state: components["schemas"]["JobState"];
            /**
             * @description Coarse execution stage for UI polling.
             * @enum {string}
             */
            stage: "queued" | "retrying" | "downloading" | "transcribing" | "finalizing" | "completed" | "failed" | "cancelled";
            progress_pct: number;
            attempt: number;
            max_attempts: number;
            cancelable: boolean;
            error_code?: string;
            error_message?: string;
            /** Format: int64 */
            download_ms?: number;
            /** Format: int64 */
            inference_ms?: number;
            /** Format: int64 */
            total_ms?: number;
            /** Format: date-time */
            updated_at: string;
        };
        CreateJobRequest: {
            /** Format: uri */
            youtube_url?: string;
            /**
             * @default auto
             * @enum {string}
             */
            device: "auto" | "cpu" | "cuda";
            /** @default 0 */
            start_sec: number;
        } | unknown;
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                [key: string]: string;
            };
        };
        ErrorResponse: {
            error_code: string;
            message: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Operation not allowed in current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        JobID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listJobs: {
        parameters: {
            query?: {
                /** @description Maximum number of jobs to return. */
                limit?: number;
                /** @description Return only jobs created before this timestamp (RFC3339). */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Job created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getJobProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job progress snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobProgress"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadMidi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MIDI file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/midi": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Job not yet completed */
            409: components["responses"]["Conflict"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description One or more dependencies unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
